# Stack: data-services — Database, cache, and message queue
# 3 services: db-postgres, db-redis, mq-rabbitmq
# Networks: app-backend-net (external)

services:
  db-postgres:
    image: postgres:16-alpine
    container_name: db-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: appdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    labels:
      app.tier: "database"
      app.env: "production"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - default
      - app-backend-net
    restart: unless-stopped

  db-redis:
    image: redis:7-alpine
    container_name: db-redis
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru
    labels:
      app.tier: "cache"
      app.env: "production"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - default
      - app-backend-net
    restart: unless-stopped

  mq-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: mq-rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    labels:
      app.tier: "messaging"
      app.env: "production"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - default
      - app-backend-net
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  default:
    name: data-services-net
  app-backend-net:
    external: true
