# Stack: staging-dev — Staging + development environments + monitoring
# 4 services: staging-web, staging-api, dev-web, monitoring-prometheus

services:
  staging-web:
    image: nginx:alpine
    container_name: staging-web
    labels:
      app.tier: "web"
      app.env: "staging"
    restart: unless-stopped

  staging-api:
    image: httpd:alpine
    container_name: staging-api
    labels:
      app.tier: "api"
      app.env: "staging"
    restart: unless-stopped

  dev-web:
    image: nginx:alpine
    container_name: dev-web
    labels:
      app.tier: "web"
      app.env: "development"
    restart: "no"

  monitoring-prometheus:
    image: prom/prometheus:latest
    container_name: monitoring-prometheus
    ports:
      - "9090:9090"
    labels:
      app.tier: "monitoring"
      app.env: "infrastructure"
    restart: unless-stopped
