# Stack: web-platform — Web tier + API gateway + cron + eBPF tracing
# 6 services: web-frontend, web-backend-1, web-backend-2, app-gateway, app-cron, beyla
# Networks: app-frontend-net (external), app-backend-net (external)

services:
  web-frontend:
    image: nginx:alpine
    container_name: web-frontend
    ports:
      - "8080:80"
    labels:
      app.tier: "web"
      app.env: "production"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - default
      - app-frontend-net
    restart: unless-stopped

  web-backend-1:
    image: httpd:alpine
    container_name: web-backend-1
    labels:
      app.tier: "web"
      app.env: "production"
      app.role: "backend"
    healthcheck:
      test: ["CMD", "httpd", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  web-backend-2:
    image: httpd:alpine
    container_name: web-backend-2
    labels:
      app.tier: "web"
      app.env: "production"
      app.role: "backend"
    healthcheck:
      test: ["CMD", "httpd", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # API gateway — bridges frontend and backend nets
  app-gateway:
    image: nginx:alpine
    container_name: app-gateway
    command:
      - sh
      - -c
      - |
        printf 'server {\n  listen 80;\n  location / {\n    return 200 "gateway ok\\n";\n    add_header Content-Type text/plain;\n  }\n  location /api {\n    proxy_pass http://app-api:8000;\n    proxy_connect_timeout 2s;\n    proxy_read_timeout 5s;\n  }\n}\n' > /etc/nginx/conf.d/default.conf
        nginx -g 'daemon off;'
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-frontend-net
      - app-backend-net
    labels:
      app.tier: "gateway"
      app.env: "production"
      app.role: "proxy"
    restart: unless-stopped

  # Scheduled job that hits the API gateway every 30s
  app-cron:
    image: alpine:latest
    container_name: app-cron
    command: >
      sh -c "
      while true; do
        echo \"[app-cron] Hitting app-gateway...\";
        wget -q -O- --timeout=5 http://app-gateway/ 2>&1 || echo '  gateway: FAIL';
        sleep 30;
      done"
    networks:
      - app-frontend-net
    labels:
      app.tier: "cron"
      app.env: "production"
      app.role: "scheduler"
    restart: unless-stopped

  # Grafana Beyla — eBPF auto-instrumentation for all HTTP services in this stack
  beyla:
    image: grafana/beyla:latest
    container_name: web-platform-beyla
    privileged: true
    pid: "host"
    init: true
    environment:
      BEYLA_OPEN_PORT: "80"
      BEYLA_SERVICE_NAMESPACE: "web-platform"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://host.docker.internal:3051/api/traces/otlp"
      OTEL_EXPORTER_OTLP_PROTOCOL: "http/json"
      OTEL_METRICS_EXPORTER: "none"
      OTEL_EXPORTER_OTLP_HEADERS: "X-API-Key=ebpf-trace-key-change-me"
      BEYLA_TRACE_PRINTER: "disabled"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /sys/kernel/security:/sys/kernel/security
    labels:
      app.tier: "observability"
      app.env: "production"
      app.role: "ebpf-tracer"
    restart: unless-stopped

networks:
  default:
    name: web-platform-net
  app-frontend-net:
    external: true
  app-backend-net:
    external: true
