import { describe, it, expect } from 'vitest';
import { emittedLevel, detectLevel, resolveLevel, parseLogs } from './log-viewer';

/**
 * The log level column was generated by grep and presented as if the emitter
 * had set it.
 *
 * `detectLevel` is a keyword match over the whole line, so the visible row
 * `module: "trace-store"` was badged DEBUG purely because it contains the word
 * "trace". The same function labels `no errors found` as ERROR and
 * `warning: none` as WARN. This is the field an operator triages on during an
 * incident, and roughly half the rows on screen carried a fabricated one.
 *
 * The heuristic still exists — a plain-text container log has nothing else to
 * go on — but a guess is now marked as a guess, and a level the record states
 * about itself takes precedence.
 */
describe('emittedLevel', () => {
  it('reads a pino string level', () => {
    expect(emittedLevel('{"level":"warn","msg":"disk filling"}')).toBe('warn');
  });

  it('reads a pino numeric level', () => {
    expect(emittedLevel('{"level":50,"msg":"boom"}')).toBe('error');
    expect(emittedLevel('{"level":30,"msg":"ok"}')).toBe('info');
    expect(emittedLevel('{"level":20,"msg":"detail"}')).toBe('debug');
  });

  it('reads a level prefix', () => {
    expect(emittedLevel('INFO: Received shutdown signal')).toBe('info');
    expect(emittedLevel('[WARN] cache miss')).toBe('warn');
  });

  it('returns null when the record states nothing', () => {
    expect(emittedLevel('module: "trace-store"')).toBeNull();
    expect(emittedLevel('no error found')).toBeNull();
  });
});

describe('resolveLevel', () => {
  it('marks a keyword match as a guess, not a fact', () => {
    // The exact reported line.
    const resolved = resolveLevel('module: "trace-store"');
    expect(resolved.level).toBe('debug');
    expect(resolved.levelSource).toBe('guessed');
  });

  it('marks a keyword false positive as a guess', () => {
    // A line reporting the *absence* of an error is badged ERROR by the
    // keyword pass. (Note the singular: the regex is word-bounded, so
    // "no errors found" does not match — the plural was reported as a false
    // positive but is not one.)
    expect(resolveLevel('no error found')).toEqual({ level: 'error', levelSource: 'guessed' });
  });

  it('prefers what the record declares over what the text contains', () => {
    // Declares info; the word "error" appears in the message body. The
    // declaration wins, and it is a fact rather than a guess.
    const resolved = resolveLevel('{"level":"info","msg":"no error occurred"}');
    expect(resolved).toEqual({ level: 'info', levelSource: 'emitted' });
  });

  it('reports no source when there is nothing to go on', () => {
    expect(resolveLevel('count: 27')).toEqual({ level: 'unknown', levelSource: 'none' });
  });

  it('keeps detectLevel available for callers that want the raw guess', () => {
    expect(detectLevel('module: "trace-store"')).toBe('debug');
  });
});

describe('parseLogs', () => {
  it('carries levelSource onto every entry', () => {
    const entries = parseLogs({
      containerId: 'c1',
      containerName: 'api',
      logs: ['INFO: started', 'module: "trace-store"', 'count: 27'].join('\n'),
    });

    expect(entries.map((e) => [e.level, e.levelSource])).toEqual([
      ['info', 'emitted'],
      ['debug', 'guessed'],
      ['unknown', 'none'],
    ]);
  });
});
