import { beforeAll, afterAll, describe, it, expect, vi, beforeEach } from 'vitest';
import { setConfigForTest, resetConfig } from '@dashboard/core/config/index.js';

// Generate mock metric data. Timestamps come off a FIXED base (not Date.now())
// so cpu and memory series generated by separate calls share timestamps — real
// co-collected metrics do, and the detector now pairs them by timestamp (#1362).
const FIXED_BASE = new Date('2026-02-07T00:00:00.000Z').getTime();
function generateMetrics(count: number, baseValue: number) {
  return Array.from({ length: count }, (_, i) => ({
    id: i,
    endpoint_id: 1,
    container_id: 'container-1',
    container_name: 'test',
    metric_type: 'cpu' as const,
    value: baseValue + (Math.random() - 0.5) * 5,
    timestamp: new Date(FIXED_BASE - (count - i) * 60000).toISOString(),
  }));
}

// DI pattern — getMetrics is passed as a parameter, no @dashboard/observability needed
const mockGetMetrics = vi.fn();

import {
  detectAnomalyIsolationForest,
  getOrTrainModel,
  clearModelCache,
  pairByTimestamp,
} from '../services/isolation-forest-detector.js';


describe('pairByTimestamp (#1362)', () => {
  const m = (timestamp: string, value: number) =>
    ({ timestamp, value, container_id: 'c', container_name: 'x', endpoint_id: 1, metric_type: 'cpu' }) as never;

  it('joins cpu + memory on equal timestamps', () => {
    const cpu = [m('2026-01-01T00:00:00.000Z', 1), m('2026-01-01T00:01:00.000Z', 2)];
    const mem = [m('2026-01-01T00:00:00.000Z', 10), m('2026-01-01T00:01:00.000Z', 20)];
    expect(pairByTimestamp(cpu, mem)).toEqual([[1, 10], [2, 20]]);
  });

  it('drops samples with no timestamp match instead of mis-pairing by index', () => {
    // memory is missing the 00:01 sample. Index-pairing would wrongly pair
    // cpu@00:01 with mem@00:02; timestamp-join drops the unmatched cpu sample.
    const cpu = [m('t0', 1), m('t1', 2), m('t2', 3)];
    const mem = [m('t0', 10), m('t2', 30)];
    expect(pairByTimestamp(cpu, mem)).toEqual([[1, 10], [3, 30]]);
  });

  it('returns no pairs when the two series do not overlap', () => {
    expect(pairByTimestamp([m('a', 1)], [m('b', 2)])).toEqual([]);
  });
});

beforeAll(() => {
    setConfigForTest({
      ISOLATION_FOREST_ENABLED: true,
      ISOLATION_FOREST_TREES: 50,
      ISOLATION_FOREST_SAMPLE_SIZE: 64,
      ISOLATION_FOREST_CONTAMINATION: 0.1,
      ISOLATION_FOREST_RETRAIN_HOURS: 6,
    });
});

afterAll(() => {
  resetConfig();
});

describe('isolation-forest-detector', () => {
  beforeEach(() => {
    clearModelCache();
    mockGetMetrics.mockReset();
  });

  it('returns null when insufficient data', async () => {
    mockGetMetrics.mockResolvedValue([]);
    const result = await getOrTrainModel('container-1', mockGetMetrics);
    expect(result).toBeNull();
  });

  it('trains and returns model with sufficient data', async () => {
    mockGetMetrics
      .mockResolvedValueOnce(generateMetrics(100, 50)) // cpu
      .mockResolvedValueOnce(generateMetrics(100, 60)); // memory

    const model = await getOrTrainModel('container-1', mockGetMetrics);
    expect(model).not.toBeNull();
  });

  it('uses cached model on subsequent calls', async () => {
    const cpuData = generateMetrics(100, 50);
    const memData = generateMetrics(100, 60);
    mockGetMetrics
      .mockResolvedValueOnce(cpuData)
      .mockResolvedValueOnce(memData);

    const model1 = await getOrTrainModel('container-1', mockGetMetrics);
    expect(model1).not.toBeNull();

    // Second call should use cache (no additional getMetrics calls)
    const model2 = await getOrTrainModel('container-1', mockGetMetrics);
    expect(model2).toBe(model1);
    expect(mockGetMetrics).toHaveBeenCalledTimes(2); // Only the first two calls
  });

  it('detects anomaly with trained model', async () => {
    mockGetMetrics
      .mockResolvedValueOnce(generateMetrics(100, 50))
      .mockResolvedValueOnce(generateMetrics(100, 60));

    const result = await detectAnomalyIsolationForest(
      'container-1', 'test-container', 'cpu', 50, 50, 60, mockGetMetrics,
    );

    expect(result).not.toBeNull();
    expect(result!.method).toBe('isolation-forest');
    expect(result!.container_id).toBe('container-1');
    expect(typeof result!.is_anomalous).toBe('boolean');
    expect(result!.z_score).toBeGreaterThanOrEqual(0);
    expect(result!.z_score).toBeLessThanOrEqual(1);
  });

  it('returns null when detection has insufficient data', async () => {
    mockGetMetrics.mockResolvedValue([]);

    const result = await detectAnomalyIsolationForest(
      'container-no-data', 'test', 'cpu', 50, 50, 60, mockGetMetrics,
    );

    expect(result).toBeNull();
  });

  // #1361 — production determinism. NOTE: this test deliberately does NOT
  // monkey-patch Math.random; reproducibility must come from a seed derived
  // inside the detector, not from a test harness stubbing the global RNG.
  it('produces a reproducible model across retrains in the same window', async () => {
    // Identical training data for both trainings, so the ONLY variable is the
    // forest's internal RNG.
    const cpuData = generateMetrics(100, 50);
    const memData = generateMetrics(100, 60);
    mockGetMetrics
      .mockResolvedValueOnce(cpuData).mockResolvedValueOnce(memData)
      .mockResolvedValueOnce(cpuData).mockResolvedValueOnce(memData);

    const m1 = await getOrTrainModel('container-1', mockGetMetrics);
    const s1 = m1!.anomalyScore([50, 60]);

    clearModelCache();

    const m2 = await getOrTrainModel('container-1', mockGetMetrics);
    const s2 = m2!.anomalyScore([50, 60]);

    expect(s2).toBe(s1);
  });

  it('uses a different seed per container (models are not all identical)', async () => {
    const cpuData = generateMetrics(100, 50);
    const memData = generateMetrics(100, 60);
    mockGetMetrics
      .mockResolvedValueOnce(cpuData).mockResolvedValueOnce(memData)
      .mockResolvedValueOnce(cpuData).mockResolvedValueOnce(memData);

    const mA = await getOrTrainModel('container-A', mockGetMetrics);
    const mB = await getOrTrainModel('container-B', mockGetMetrics);

    // Same data, different container id → different seed → different partitions.
    const probes = [[50, 60], [80, 90], [10, 20]];
    const anyDifferent = probes.some((p) => mA!.anomalyScore(p) !== mB!.anomalyScore(p));
    expect(anyDifferent).toBe(true);
  });
});
